name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy_production:
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit

  smoke_test:
    needs: [deploy_production]
    uses: ./.github/workflows/_smoke.yml
    with:
      url: https://happy-sea-092e38b03.7.azurestaticapps.net
